name: Crystal CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Crystal Ameba Linter
        id: crystal-ameba
        uses: crystal-ameba/github-action@v0.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: shards install
      - name: Run tests
        run: crystal spec
